"""add starting_balance + estimated_income to prefs

Revision ID: 1820e2fbfcc9
Revises: 9fd2a8df45ed
Create Date: 2026-09-29 17:38:29.684414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1820e2fbfcc9'
down_revision: Union[str, Sequence[str], None] = '9fd2a8df45ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_balance_inr', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('estimated_monthly_income_inr', sa.Numeric(precision=12, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('estimated_monthly_income_inr')
        batch_op.drop_column('starting_balance_inr')

    # ### end Alembic commands ###
