"""init obligation graph schema

Revision ID: 9fd2a8df45ed
Revises: 
Create Date: 2026-09-29 17:26:41.447482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd2a8df45ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_category', sa.String(), nullable=False),
    sa.Column('prereq_category', sa.String(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dependency_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependency_templates_parent_category'), ['parent_category'], unique=False)

    op.create_table('obligation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('vendor_normalized', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('resolved_date', sa.Date(), nullable=True),
    sa.Column('was_late', sa.Boolean(), nullable=False),
    sa.Column('verification_final_state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('obligation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obligation_history_user_id'), ['user_id'], unique=False)

    op.create_table('obligations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('vendor_normalized', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('obligation_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('flexibility_window', sa.Integer(), nullable=False),
    sa.Column('recurrence', sa.JSON(), nullable=True),
    sa.Column('penalty', sa.JSON(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('urgency_tier', sa.String(), nullable=False),
    sa.Column('verification_state', sa.String(), nullable=False),
    sa.Column('signal_extracted', sa.JSON(), nullable=True),
    sa.Column('signal_pre_debit', sa.JSON(), nullable=True),
    sa.Column('signal_debit', sa.JSON(), nullable=True),
    sa.Column('signal_receipt', sa.JSON(), nullable=True),
    sa.Column('batchable', sa.Boolean(), nullable=False),
    sa.Column('batch_group', sa.String(), nullable=True),
    sa.Column('trigger_event', sa.JSON(), nullable=True),
    sa.Column('auto_pay_enabled', sa.Boolean(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('obligations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obligations_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligations_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligations_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligations_vendor_normalized'), ['vendor_normalized'], unique=False)

    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hard_floor_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('soft_cushion_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('salary_day_of_month', sa.Integer(), nullable=True),
    sa.Column('admin_day_offset', sa.Integer(), nullable=False),
    sa.Column('aggressiveness', sa.String(), nullable=False),
    sa.Column('voice_enabled', sa.Boolean(), nullable=False),
    sa.Column('channels_enabled', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('vendor_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('vendor_normalized', sa.String(), nullable=False),
    sa.Column('avg_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('std_dev_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avg_day_of_month', sa.Integer(), nullable=True),
    sa.Column('recurrence_frequency', sa.String(), nullable=True),
    sa.Column('recurrence_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('miss_rate', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('seasonal_multipliers', sa.JSON(), nullable=False),
    sa.Column('next_predicted', sa.Date(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vendor_normalized', name='uq_vendor_pattern')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('linked_obligation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['linked_obligation_id'], ['obligations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prerequisite_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obligation_id', sa.String(), nullable=False),
    sa.Column('prerequisite_id', sa.String(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('edge_kind', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obligation_id', 'prerequisite_id', name='uq_edge')
    )
    with op.batch_alter_table('prerequisite_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prerequisite_edges_obligation_id'), ['obligation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prerequisite_edges_prerequisite_id'), ['prerequisite_id'], unique=False)

    op.create_table('processed_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=False),
    sa.Column('obligation_id', sa.String(), nullable=True),
    sa.Column('raw_snippet', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_type', 'source_ref', name='uq_signal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_signals')
    with op.batch_alter_table('prerequisite_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prerequisite_edges_prerequisite_id'))
        batch_op.drop_index(batch_op.f('ix_prerequisite_edges_obligation_id'))

    op.drop_table('prerequisite_edges')
    op.drop_table('documents')
    op.drop_table('vendor_patterns')
    op.drop_table('user_preferences')
    with op.batch_alter_table('obligations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obligations_vendor_normalized'))
        batch_op.drop_index(batch_op.f('ix_obligations_user_id'))
        batch_op.drop_index(batch_op.f('ix_obligations_status'))
        batch_op.drop_index(batch_op.f('ix_obligations_due_date'))
        batch_op.drop_index(batch_op.f('ix_obligations_category'))

    op.drop_table('obligations')
    with op.batch_alter_table('obligation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obligation_history_user_id'))

    op.drop_table('obligation_history')
    with op.batch_alter_table('dependency_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependency_templates_parent_category'))

    op.drop_table('dependency_templates')
    # ### end Alembic commands ###
